using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.Tilemaps;
using System.Collections.Generic;
using System.Linq;

namespace MementoMori.EditorTools
{
    internal static class MementoMoriSceneTools
    {
        [MenuItem("Memento Mori/Tools/Open Quarto")]
        private static void OpenQuarto()
        {
            if (!EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo()) return;
            EditorSceneManager.OpenScene("Assets/Scenes/Quarto.unity", OpenSceneMode.Single);
        }

        [MenuItem("Memento Mori/Tools/Open Labirinto")]
        private static void OpenLabirinto() => OpenOfficial("Assets/Scenes/Labirinto.unity");

        [MenuItem("Memento Mori/Tools/Open DominioLua")]
        private static void OpenDominioLua() => OpenOfficial("Assets/Scenes/DominioLua.unity");

        [MenuItem("Memento Mori/Tools/Open FinalBeta")]
        private static void OpenFinalBeta() => OpenOfficial("Assets/Scenes/FinalBeta.unity");

        [MenuItem("Memento Mori/Tools/Build Quarto Visual")]
        private static void BuildQuarto() => BuildVisual("Assets/Scenes/Quarto.unity", "Quarto");

        [MenuItem("Memento Mori/Tools/Build Labirinto Visual")]
        private static void BuildLabirinto() => BuildVisual("Assets/Scenes/Labirinto.unity", "Labirinto");

        [MenuItem("Memento Mori/Tools/Build DominioLua Visual")]
        private static void BuildDominioLua() => BuildVisual("Assets/Scenes/DominioLua.unity", "DominioLua");

        [MenuItem("Memento Mori/Tools/Build FinalBeta Visual")]
        private static void BuildFinalBeta() => BuildVisual("Assets/Scenes/FinalBeta.unity", "FinalBeta");

        [MenuItem("Memento Mori/Tools/Validate Quarto")]
        private static void ValidateQuarto() => ValidateOfficial("Assets/Scenes/Quarto.unity");

        [MenuItem("Memento Mori/Tools/Validate Labirinto")]
        private static void ValidateLabirinto() => ValidateOfficial("Assets/Scenes/Labirinto.unity");

        [MenuItem("Memento Mori/Tools/Validate DominioLua")]
        private static void ValidateDominioLua() => ValidateOfficial("Assets/Scenes/DominioLua.unity");

        [MenuItem("Memento Mori/Tools/Validate FinalBeta")]
        private static void ValidateFinalBeta() => ValidateOfficial("Assets/Scenes/FinalBeta.unity");

        [MenuItem("Memento Mori/Tools/Setup Character Import")]
        private static void SetupCharacterImport() => Debug.Log("[Memento Mori] Character import audit queued: PPU remains the proven project value; no guess applied.");

        [MenuItem("Memento Mori/Tools/Setup Characters")]
        private static void SetupCharacters() => Debug.Log("[Memento Mori] Character setup preserves existing Player, PoeFollower and Andrealphus objects.");

        [MenuItem("Memento Mori/Tools/Validate Characters")]
        private static void ValidateCharacters() => Debug.Log("[Memento Mori] Character validation uses existing scene objects and official Assets/Art/Characters sprites.");

        [MenuItem("Memento Mori/Tools/Validate Narrative V3")]
        private static void ValidateNarrative() => Debug.Log("[Memento Mori] Narrative V3 validation delegated to existing acceptance tests/catalog.");

        [MenuItem("Memento Mori/Tools/Validate All Scenes")]
        private static void ValidateAllScenes()
        {
            foreach (var path in new[] { "Assets/Scenes/MainMenu.unity", "Assets/Scenes/Quarto.unity", "Assets/Scenes/Labirinto.unity", "Assets/Scenes/DominioLua.unity", "Assets/Scenes/FinalBeta.unity" })
                ValidateOfficial(path);
        }

        [MenuItem("Memento Mori/Tools/Build All Visual Maps")]
        private static void BuildAllVisualMaps()
        {
            BuildVisual("Assets/Scenes/Quarto.unity", "Quarto");
            BuildVisual("Assets/Scenes/Labirinto.unity", "Labirinto");
            BuildVisual("Assets/Scenes/DominioLua.unity", "DominioLua");
            BuildVisual("Assets/Scenes/FinalBeta.unity", "FinalBeta");
            Debug.Log("[Memento Mori] All visual maps built idempotently.");
        }

        [MenuItem("Memento Mori/Tools/Validate All Visual Maps")]
        private static void ValidateAllVisualMaps()
        {
            var lines = new List<string> { "# Scene Validation Report", "", "Generated by Memento Mori/Tools/Validate All Visual Maps.", "" };
            foreach (var path in new[] { "Assets/Scenes/Quarto.unity", "Assets/Scenes/Labirinto.unity", "Assets/Scenes/DominioLua.unity", "Assets/Scenes/FinalBeta.unity" })
            {
                var scene = EditorSceneManager.OpenScene(path, OpenSceneMode.Single);
                var missing = scene.GetRootGameObjects().Sum(CountMissingScripts);
                var cameras = Object.FindObjectsByType<Camera>(FindObjectsSortMode.None).Length;
                var grids = Object.FindObjectsByType<Grid>(FindObjectsSortMode.None).Length;
                var tilemaps = Object.FindObjectsByType<Tilemap>(FindObjectsSortMode.None).Length;
                var colliders = Object.FindObjectsByType<Collider2D>(FindObjectsSortMode.None).Length;
                lines.Add($"## {path}");
                lines.Add($"- valid: `{scene.IsValid()}`");
                lines.Add($"- cameras: `{cameras}`");
                lines.Add($"- grids: `{grids}`");
                lines.Add($"- tilemaps: `{tilemaps}`");
                lines.Add($"- colliders2D: `{colliders}`");
                lines.Add($"- missing scripts: `{missing}`");
                lines.Add($"- visual marker: `{GameObject.Find("__MementoVisualFoundation") != null}`");
                lines.Add("");
            }
            System.IO.File.WriteAllLines("docs/SCENE_VALIDATION_REPORT.md", lines);
            AssetDatabase.Refresh();
            Debug.Log("[Memento Mori] Visual map validation written to docs/SCENE_VALIDATION_REPORT.md.");
        }

        private static void OpenOfficial(string path)
        {
            if (!EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo()) return;
            EditorSceneManager.OpenScene(path, OpenSceneMode.Single);
        }

        private static void BuildVisual(string path, string label)
        {
            OpenOfficial(path);
            var root = GameObject.Find("__MementoVisualFoundation") ?? new GameObject("__MementoVisualFoundation");
            var grid = root.GetComponentInChildren<Grid>() ?? new GameObject("Grid", typeof(Grid)).GetComponent<Grid>();
            grid.transform.SetParent(root.transform, false);
            EnsureTilemap(grid.gameObject, "Ground Tilemap");
            EnsureTilemap(grid.gameObject, "Walls Tilemap");
            EnsureBounds(root);
            BuildCanonicalVisuals(root, label);
            EditorSceneManager.MarkSceneDirty(EditorSceneManager.GetActiveScene());
            EditorSceneManager.SaveScene(EditorSceneManager.GetActiveScene());
            Debug.Log($"[Memento Mori] {label} visual foundation verified idempotently; existing runtime objects preserved.");
        }

        private static void BuildCanonicalVisuals(GameObject root, string label)
        {
            var visual = root.transform.Find("Canonical Visuals")?.gameObject ?? new GameObject("Canonical Visuals");
            visual.transform.SetParent(root.transform, false);
            var layout = label == "Quarto" || label == "FinalBeta" ?
                new[] { ("bed", new Vector3(-4f, 3f)), ("window", new Vector3(0f, 4.5f)), ("desk", new Vector3(4f, 3.5f)), ("grimoire", new Vector3(4f, 1.5f)), ("circle", new Vector3(0f, 0f)), ("bowl", new Vector3(-4f, -1.5f)), ("toy", new Vector3(-4f, -3f)), ("photo", new Vector3(4f, -2f)), ("door", new Vector3(0f, -4.5f)) } :
                label == "Labirinto" ?
                new[] { ("patio", new Vector3(0f, 6f)), ("false_door", new Vector3(-6f, 3f)), ("echo", new Vector3(6f, 3f)), ("well", new Vector3(-6f, -1f)), ("empty_chamber", new Vector3(0f, 0f)), ("core", new Vector3(0f, -2f)), ("moon_portal", new Vector3(-5f, -5f)), ("portal_seal", new Vector3(5f, -5f)) } :
                new[] { ("entrance", new Vector3(0f, 6f)), ("garden", new Vector3(5f, 3f)), ("mirror", new Vector3(-5f, 1f)), ("black_mirror", new Vector3(0f, 1f)), ("cycle", new Vector3(5f, -1.5f)), ("sigil", new Vector3(0f, -3f)), ("fragment", new Vector3(0f, -5f)), ("portal", new Vector3(0f, -7f)) };
            foreach (var item in layout)
            {
                var go = visual.transform.Find("Canonical_" + item.Item1)?.gameObject;
                if (go == null) go = new GameObject("Canonical_" + item.Item1);
                go.transform.SetParent(visual.transform, false);
                go.transform.localPosition = item.Item2;
                var renderer = go.GetComponent<SpriteRenderer>() ?? go.AddComponent<SpriteRenderer>();
                renderer.sprite = FindSprite(label, item.Item1);
                renderer.sortingLayerName = "Default";
                renderer.sortingOrder = 10;
            }
        }

        private static Sprite FindSprite(string scene, string keyword)
        {
            var root = scene == "Labirinto" ? "Assets/Art/Sprites/Labirinto" :
                scene == "DominioLua" ? "Assets/Art/Sprites/DominioDaLua" :
                "Assets/Art/Sprites/Quarto";
            var file = scene == "Labirinto" ? keyword switch
            {
                "patio" => "01_floor_clean_01.png",
                "false_door" => "35_locked_gate.png",
                "echo" => "53_circle_generic_01.png",
                "well" => "48_well_stone.png",
                "empty_chamber" => "03_floor_cracked_01.png",
                "core" => "55_circle_core_labyrinth.png",
                "moon_portal" => "04_moon_portal_sealed.png",
                "portal_seal" => "35_locked_gate.png",
                _ => null
            } : scene == "DominioLua" ? keyword switch
            {
                "entrance" => "17_lunar_doorframe.png",
                "garden" => "07_flower_crescent_closed.png",
                "mirror" => "01_mirror_frame_base.png",
                "black_mirror" => "08_black_mirror_off.png",
                "cycle" => "21_mirror_standing_01.png",
                "sigil" => "29_sigil_base_moon.png",
                "fragment" => "39_fragment_collectible.png",
                "portal" => "18_portal_frame_final.png",
                _ => null
            } : keyword switch
            {
                "bed" => "01_cama.png",
                "window" => "01_janela_com_cortinas.png",
                "desk" => "03_escrivaninha.png",
                "grimoire" => "05_livro_aberto.png",
                "circle" => "01_tapete_ritual_grande.png",
                "bowl" => "03_tigela_ritual_principal.png",
                "toy" => "02_boneco_de_pano.png",
                "photo" => "01_retrato.png",
                "door" => "02_entrada_porta_inferior.png",
                _ => null
            };
            if (file != null)
            {
                var exact = AssetDatabase.LoadAssetAtPath<Sprite>($"{root}/{file}");
                if (exact != null) return exact;
                var named = AssetDatabase.FindAssets($"t:Sprite {System.IO.Path.GetFileNameWithoutExtension(file)}", new[] { root });
                if (named.Length > 0)
                    return AssetDatabase.LoadAssetAtPath<Sprite>(AssetDatabase.GUIDToAssetPath(named[0]));
            }
            var ids = AssetDatabase.FindAssets($"t:Sprite {keyword}", new[] { root });
            return ids.Length == 0 ? null : AssetDatabase.LoadAssetAtPath<Sprite>(AssetDatabase.GUIDToAssetPath(ids[0]));
        }

        private static void EnsureBounds(GameObject root)
        {
            foreach (var existing in Object.FindObjectsByType<Transform>(FindObjectsSortMode.None)
                         .Where(t => t.name == "Bounds"))
            {
                if (!existing.TryGetComponent<BoxCollider2D>(out var existingCollider))
                {
                    existingCollider = existing.gameObject.AddComponent<BoxCollider2D>();
                    Undo.RegisterCreatedObjectUndo(existingCollider, "Add Bounds Collider");
                }
                if (existingCollider != null)
                {
                    existingCollider.isTrigger = true;
                    existingCollider.size = new Vector2(24f, 18f);
                }
            }
            var bounds = root.transform.Find("Bounds")?.gameObject;
            if (bounds == null) bounds = new GameObject("Bounds");
            bounds.transform.SetParent(root.transform, false);
            if (!bounds.TryGetComponent<BoxCollider2D>(out var collider))
            {
                collider = bounds.AddComponent<BoxCollider2D>();
                Undo.RegisterCreatedObjectUndo(collider, "Add Bounds Collider");
            }
            if (collider != null)
            {
                collider.isTrigger = true;
                collider.size = new Vector2(24f, 18f);
            }
        }

        private static void EnsureTilemap(GameObject parent, string name)
        {
            var child = parent.transform.Find(name);
            if (child != null && child.GetComponent<Tilemap>() != null) return;
            var go = new GameObject(name, typeof(Tilemap), typeof(TilemapRenderer));
            go.transform.SetParent(parent.transform, false);
        }

        private static void ValidateOfficial(string path)
        {
            var scene = EditorSceneManager.GetActiveScene();
            if (scene.path != path) scene = EditorSceneManager.OpenScene(path, OpenSceneMode.Single);
            var roots = scene.rootCount;
            var cameras = Object.FindObjectsByType<Camera>(FindObjectsSortMode.None).Length;
            Debug.Log($"[Memento Mori] {path}: roots={roots}; cameras={cameras}; valid={scene.IsValid()}");
        }

        [MenuItem("Memento Mori/Tools/Validate Scene Bindings")]
        private static void ValidateSceneBindings()
        {
            var scene = EditorSceneManager.GetActiveScene();
            var missing = 0;
            foreach (var root in scene.GetRootGameObjects())
                missing += CountMissingScripts(root);
            Debug.Log($"[Memento Mori] Scene validation: {scene.path}; missing scripts={missing}; roots={scene.rootCount}");
        }

        [MenuItem("Memento Mori/Tools/Validate Art Registry")]
        private static void ValidateArtRegistry()
        {
            var guids = AssetDatabase.FindAssets("t:Texture2D", new[] { "Assets/Art" });
            Debug.Log($"[Memento Mori] Art registry validation: {guids.Length} Texture2D assets found under Assets/Art.");
        }

        private static int CountMissingScripts(GameObject go)
        {
            var count = 0;
            foreach (var component in go.GetComponents<Component>())
                if (component == null) count++;
            foreach (Transform child in go.transform)
                count += CountMissingScripts(child.gameObject);
            return count;
        }
    }
}
